### ISSUE TITLE
High codespace CPU utilization detected

### ISSUE THREAD

**Issue by iaindillingham** [opensafely/waiting-list#143]
When running this study in a Codespace, the Codespace reports:

> High codespace CPU (100%) utilization detected. Consider stopping some processes for the best experience.

Team REX will investigate.

**Comment by lucyb** [comment]
It would be worth trying to recreate this in a codespace in Andrea's repo, to see if we get the same error when using `run_all`. 

This error isn't necessarily a problem, as we expect some scripts to be CPU intensive and the Codespace isn't used for anything else. Howeve,r it would be worth us being aware of the issue and possibly documenting it.

**Comment by StevenMaude** [comment]
I was able to reproduce it on commit 54ec249c227a51907c7bf2b5592029499ff2b061 which was the current `main` branch at that time.

![high-codespace-cpu-notification](https://github.com/opensafely/waiting-list/assets/3818079/5607826f-a38e-4c49-9289-ccc5933e7ff5)

Nonetheless, the OpenSAFELY project ran without error.

I can't find any obvious way of disabling the notification otherwise. (I tried looking under Settings for `github.codespaces` which has some options, but not one for this notification.)

**Comment by lucyb** [comment]
Thanks for investigating Steve. I'm going to close the ticket, since I don't think we should do any more work on it for now.

We talked briefly about adding in some documentation, but I don't think that's necessary right now. If this happens again, then the process is for someone to contact our team and we can investigate/get back to them. If it keeps happening, then we should look at making some changes, but by then we'll also have more information about where we should make those changes.
